# 1inch MCP Server Configuration
# Simplified configuration with only properly mapped properties

# Application Info
quarkus:
  application:
    name: 1inch-mcp-server
    version: 1.0.0
  
  # Logging Configuration  
  log:
    level: INFO
    category:
      "io.oneinch.mcp": DEBUG
    console:
      json: false

# 1inch API Configuration
oneinch:
  api:
    key: ${ONEINCH_API_KEY:}
    base-url: https://api.1inch.dev

# MCP Configuration  
mcp:
  server:
    name: 1inch-mcp-server
    version: 1.0.0
  rate-limit:
    requests-per-minute: 60
    burst-capacity: 10
  transport:
    mode: BOTH
    http:
      root-path: /mcp
      host: 0.0.0.0
      port: 8080
      enable-sse: true
      enable-streamable: true
      include-query-params: false
      request-timeout-ms: 30000
      max-message-size: 1048576
    security:
      enabled: true
      auth-method: API_KEY
      api-key-header: X-API-Key
    cors:
      enabled: true
      allowed-origins:
        - "*"
      allowed-methods:
        - GET
        - POST  
        - OPTIONS
      allowed-headers:
        - Content-Type
        - Authorization
        - X-API-Key
      allow-credentials: true
      max-age: 3600

# Profile-specific configurations
"%dev":
  quarkus:
    log:
      level: DEBUG
  mcp:
    transport:
      security:
        enabled: false
        auth-method: NONE

"%test":
  oneinch:
    api:
      key: test-api-key
  mcp:
    transport:
      security:
        enabled: false
        auth-method: NONE

"%prod":
  quarkus:
    log:
      console:
        json: true
  mcp:
    transport:
      security:
        enabled: true
        auth-method: API_KEY
      cors:
        allowed-origins:
          - "https://claude.ai"
          - "https://cursor.sh"

# Stdio-only profile
"%stdio":
  mcp:
    transport:
      mode: STDIO

# HTTP-only profile  
"%http":
  mcp:
    transport:
      mode: HTTP_SSE
      security:
        enabled: true
        auth-method: API_KEY